'use strict';
const $ = id => document.getElementById(id);
let config, current=null, selected=null, page=1, revision=0, job=null, searchJob=null, searchData=null, cancelRequested=null, searchCancelRequested=null, importSequence=0;
const queue = new Map();
// Covers the maximum 25,000-row browser export and duplicated legacy Tk groups.
const MAX_IMPORT_BYTES = 64 * 1024 * 1024;
const defaults = {C:4,H:12,N:0,O:3,S:0,P:0,Si:0,F:0,Cl:0,Br:0,I:0,B:0,Se:0};
const number = (value,digits=Number($('precision').value)) => Number.isFinite(value) ? value.toFixed(digits) : '缺失';
function notice(message, error=false){$('notice').textContent=message;$('notice').className=error?'error':'';$('notice').hidden=!message;}
function formula(row){const f=row.formula;const keys=f.C?['C','H',...Object.keys(f).filter(e=>!['C','H'].includes(e)).sort()]:Object.keys(f).sort();return keys.filter(e=>f[e]>0).map(e=>e+(f[e]>1?f[e]:'')).join('');}
function elementInputs(){const primary=document.createElement('div');primary.className='element-grid';const detail=document.createElement('details');detail.id='advancedElements';const summary=document.createElement('summary');summary.textContent='扩展元素 · S / P / 卤素等';const advanced=document.createElement('div');advanced.className='element-grid';detail.append(summary,advanced);$('elements').append(primary,detail);for(const e of ['C','H','N','O','S','P','Si','F','Cl','Br','I','B','Se']){const label=document.createElement('label');label.textContent=e;const input=document.createElement('input');Object.assign(input,{type:'number',min:'-1',max:'1000',step:'1',value:defaults[e],id:'element-'+e});input.required=true;input.setAttribute('aria-label',e+' 元素上限');label.append(input);(['C','H','N','O'].includes(e)?primary:advanced).append(label);}}
function adductInputs(chosen){$('adducts').replaceChildren();for(const a of Object.keys(config.adducts[$('mode').value])){const label=document.createElement('label');label.className='chip';const input=document.createElement('input');input.type='checkbox';input.value=a;input.checked=chosen?chosen.includes(a):a===Object.keys(config.adducts[$('mode').value])[0];label.append(input,document.createTextNode(a));$('adducts').append(label);}updateHints();}
function readParams(){const elements={};for(const input of $('elements').querySelectorAll('input'))elements[input.id.slice(8)]=Number(input.value);return {m2z:Number($('mz').value),error_pct:Number($('pct').value),error_da:Number($('da').value),charge:Number($('charge').value),ms_mode:$('mode').value,adduct_model:[...$('adducts').querySelectorAll('input:checked')].map(i=>i.value),elements,dbe_filter:$('dbe').checked};}
function updateHints(){const p=readParams(),w=Math.max(p.m2z*p.error_pct/100,p.error_da);$('windowHint').textContent=`±${number(w,9)} Th · ±${number(w/p.m2z*1e6,3)} ppm · 中性质量 ±${number(w*p.charge,9)} Da`;$('ionHint').textContent=p.charge>1?'多电荷仅支持 [M+zH]z+ / [M−zH]z−；其他加合须单电荷':'单电荷；中性质量 = m/z − 离子质量（含电子质量修正）';}
function validParams(p){if(!p||typeof p.ms_mode!=='string'||!Object.hasOwn(config.adducts,p.ms_mode)||!Array.isArray(p.adduct_model)||!p.adduct_model.length||p.adduct_model.some(a=>typeof a!=='string'||!Object.hasOwn(config.adducts[p.ms_mode],a)))throw Error('文件离子模式或加合类型无效');for(const key of ['m2z','error_pct','error_da','charge'])if(!Number.isFinite(p[key]))throw Error('文件参数包含缺失或非法数值');if(p.m2z<=0||p.m2z>3000||!Number.isInteger(p.charge)||p.charge<1||p.charge>10||p.error_pct<0||p.error_pct>1||p.error_da<0||p.error_da>10)throw Error('文件参数超出支持范围');if(!p.elements||Array.isArray(p.elements)||typeof p.elements!=='object'||!Object.keys(p.elements).length)throw Error('文件缺少元素约束');for(const [e,n] of Object.entries(p.elements))if(!config.elements.includes(e)||!Number.isInteger(n)||n< -1||n>1000)throw Error('文件元素约束无效');if(p.charge>1&&(!p.ms_mode.startsWith('ESI')||p.adduct_model.some(a=>!['H+','H-'].includes(a))))throw Error('文件多电荷离子模型不受支持');if(p.dbe_filter!==undefined&&typeof p.dbe_filter!=='boolean')throw Error('文件DBE设置无效');}
function applyParams(p){$('mz').value=p.m2z;$('pct').value=p.error_pct;$('da').value=p.error_da??0;$('charge').value=p.charge;$('mode').value=p.ms_mode;adductInputs(p.adduct_model);for(const e of config.elements)$('element-'+e).value=p.elements[e]??0;$('dbe').checked=p.dbe_filter??true;$('advancedElements').open=Object.entries(p.elements).some(([e,n])=>!['C','H','N','O'].includes(e)&&n!==0);updateHints();}
function changed(){revision++;updateHints();if(current){$('resultState').textContent='参数已变更 · 结果陈旧';$('resultState').className='badge warning';$('jsonExport').disabled=$('csvExport').disabled=$('addSearch').disabled=true;}try{localStorage.setItem('mass-finding-draft-v2',JSON.stringify(readParams()));$('draftState').textContent='参数草稿已保存 · 结果不自动保存';}catch(_e){$('draftState').textContent='浏览器未允许保存参数草稿';}}
function setBusy(busy){$('analyze').disabled=busy;$('cancel').disabled=!busy;$('importButton').disabled=busy;$('example').disabled=busy;$('emptyExample').disabled=busy;}
async function api(path,payload){const response=await fetch(path,{method:payload===undefined?'GET':'POST',headers:payload===undefined?{}:{'Content-Type':'application/json','X-Workbench-Token':config.token},body:payload===undefined?undefined:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw Error(data.error||'请求失败');return data;}
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function poll(id,isCurrent){for(;;){await wait(180);if(!isCurrent())return null;const state=await api('/api/jobs/'+id);if(state.status!=='running')return state;}}
function display(result,caption){current=result;selected=null;page=1;$('formulaFilter').value='';$('resultCaption').textContent=caption;$('resultCount').textContent=result.results.length;$('resultState').textContent='当前输入 · 候选结果';$('resultState').className='badge';$('jsonExport').disabled=$('csvExport').disabled=false;render();}
async function analyze(event){event.preventDefault();if(job)return;job='starting';importSequence++;notice('');const params=readParams(),version=revision;let id;setBusy(true);$('cancel').disabled=true;try{validParams(params);const response=await api('/api/analyze',params);id=response.id;job=id;cancelRequested=null;$('cancel').disabled=false;$('resultState').textContent='分析中…';const state=await poll(id,()=>job===id);if(!state)return;if(state.status==='error'&&cancelRequested!==id)throw Error(state.error);if(state.status==='cancelled'||cancelRequested===id){notice('分析已取消，可修改参数后重试。');return;}if(revision!==version){notice('分析期间参数已变化，本次结果未回填。请重新生成。');return;}display(state.result,`单同位素候选 · 窗口 ±${number(state.result.metadata.tolerance_th,9)} Th · ${number(state.result.metadata.elapsed_seconds,2)} s`);if(!state.result.results.length)notice('分析完成：此离子模型、元素约束与窗口内无候选。可核对峰位或调整约束。');}catch(error){notice(error.message,true);}finally{if(!id||job===id){job=null;setBusy(false);if(!current){$('resultState').textContent='等待分析';$('resultState').className='badge neutral';}else if(revision!==version){changed();}else if($('resultState').textContent==='分析中…'){$('resultState').textContent='此前结果 · 请复核';}}}}
function visibleRows(){const q=$('formulaFilter').value.trim().toLowerCase();return (current?.results??[]).filter(r=>(formula(r)+' '+r.adduct_type+' '+r.ion_model).toLowerCase().includes(q));}
function render(){const rows=visibleRows(),size=Number($('pageSize').value),total=Math.max(1,Math.ceil(rows.length/size));page=Math.min(page,total);$('rows').replaceChildren();const start=(page-1)*size;for(const row of rows.slice(start,start+size)){const tr=document.createElement('tr');tr.tabIndex=0;tr.setAttribute('aria-label','选择 '+formula(row));if(selected===row)tr.classList.add('selected');const p=row.calculated_properties;for(const value of [formula(row),row.ion_model||row.adduct_type,number(p.predicted_mz),number(p.error_ppm,3),number(p.molecular_weight),number(p.dbr,1)]){const td=document.createElement('td');td.textContent=value;tr.append(td);}const select=()=>{selected=row;render();};tr.addEventListener('click',select);tr.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select();}});$('rows').append(tr);}$('empty').hidden=rows.length>0;if(current&&!rows.length){$('empty').querySelector('h3').textContent=current.results.length?'没有符合筛选的候选':'此窗口内无候选';$('empty').querySelector('p').textContent='核对筛选词、离子模型、元素上限与误差窗口。';}$('pageSummary').textContent=rows.length?`${start+1}–${Math.min(start+size,rows.length)} / ${rows.length} 个候选`:'尚无可显示候选';$('pageLabel').textContent=page+' / '+total;$('prev').disabled=page<=1;$('next').disabled=page>=total;$('selectedFormula').textContent=selected?formula(selected):'—';$('selectedDetail').textContent=selected?`${selected.ion_model||selected.adduct_type} · 中性质量 ${selected.calculated_properties.molecular_weight} Da · m/z ${selected.calculated_properties.predicted_mz} Th`:'选择候选查看精确质量与离子模型';$('addSearch').disabled=!selected||$('jsonExport').disabled;}
function download(content,name,type){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function csv(result){const quote=value=>'"'+String(value??'').replaceAll('"','""')+'"';let lines=[['engine_version',result.metadata?.engine_version??'legacy'],['input_params',JSON.stringify(result.input_params)],['metadata',JSON.stringify(result.metadata??{})],['formula','ion_model','adduct_type','predicted_mz_Th','neutral_mass_Da','error_Th','error_ppm','DBE']];for(const row of result.results){const p=row.calculated_properties;lines.push([formula(row),row.ion_model,row.adduct_type,p.predicted_mz,p.molecular_weight,p.error_th,p.error_ppm,p.dbr]);}return '\ufeff'+lines.map(line=>line.map(quote).join(',')).join('\r\n');}
// Input caps stop at 1000; unlimited inputs can generate larger formula counts.
function validatedImport(data){if(data?.status==='error')throw Error('文件记录了失败分析：'+(data.error||'未知错误'));if(data?.metadata!==undefined&&(!data.metadata||Array.isArray(data.metadata)||typeof data.metadata!=='object'))throw Error('文件metadata须为对象');if(!data||!Array.isArray(data.results)||data.results.length>25000||!data.input_params)throw Error('文件须包含 input_params 与 results；最多 25000 个候选');const p={...data.input_params,error_da:data.input_params.error_da??0};validParams(p);for(const row of data.results){if(!row||typeof row.formula!=='object'||Array.isArray(row.formula)||!row.formula||!Object.keys(row.formula).length)throw Error('文件含无效分子式记录');for(const [e,n]of Object.entries(row.formula))if(!config.elements.includes(e)||!Number.isSafeInteger(n)||n<0||n>10000)throw Error('文件分子式含未知元素或非法计数');if(row.ion_model!=null&&typeof row.ion_model!=='string')throw Error('文件候选离子模型须为文本');const calc=row.calculated_properties;if(!calc||!['dbr','predicted_mz','molecular_weight'].every(k=>Number.isFinite(calc[k]))||calc.predicted_mz<=0||calc.molecular_weight<=0)throw Error('文件候选缺少有限质量或DBE');if(!p.adduct_model.includes(row.adduct_type))throw Error('文件候选加合物与输入不一致');}return {...data,input_params:p};}
async function importFile(event){const file=event.target.files[0];event.target.value='';if(job)return;const sequence=++importSequence,version=revision;const isCurrent=()=>sequence===importSequence&&version===revision&&!job;if(!file)return;try{if(file.size>MAX_IMPORT_BYTES)throw Error('文件大于 64 MiB，未打开');const text=await file.text();if(!isCurrent())return;const result=validatedImport(JSON.parse(text));const restored={...result.input_params,elements:{...result.input_params.elements}};if(!result.metadata?.engine_version&&restored.elements.H===undefined)restored.elements.H=-1;applyParams(restored);revision++;display(result,`已打开：${file.name} · 原始质量保留，未重新计算`);if(result.metadata?.engine_version!=='2.0.0'){notice('历史文件：原结果按旧质量表保留，不代表已用 v2 引擎复核。重新生成可采用修正后的离子质量。');$('resultState').textContent='历史文件 · 未重新计算';$('resultState').className='badge warning';}else notice('文件与输入已恢复。显示保存的原始候选，未重新计算。');}catch(error){if(isCurrent())notice('无法打开：'+error.message+'。当前输入与结果已保留。',true);}}
function loadExample(){if(job)return;applyParams({m2z:47.049141279571,error_pct:.0005,error_da:0,charge:1,ms_mode:'ESI+',adduct_model:['H+'],elements:defaults,dbe_filter:true});changed();notice('已载入合成乙醇峰：47.049141279571 Th（[M+H]+）。点击生成候选。');}
function view(name){$('analysisView').hidden=name!=='analysis';$('searchView').hidden=name!=='search';$('viewTitle').textContent=name==='analysis'?'候选分子式':'PubChem 检索';for(const btn of document.querySelectorAll('.nav'))btn.classList.toggle('active',btn.dataset.view===name);}
function addQueue(f){if(!/^(?:[A-Z][a-z]?\d*)+$/.test(f)||f.length>100){notice('请输入简单中性分子式，如 C2H6O。',true);return;}if(!queue.has(f))queue.set(f,{status:'待检索'});renderQueue();notice('已加入检索：'+f);}
function renderQueue(){$('queueCount').textContent=queue.size;$('queue').replaceChildren();for(const [f,item] of queue){const div=document.createElement('div');div.className='queue-item';const strong=document.createElement('strong');strong.textContent=f;const query=document.createElement('button');query.textContent='查询 / 重试';query.disabled=Boolean(searchJob);query.addEventListener('click',()=>search(f));const remove=document.createElement('button');remove.textContent='移除';remove.disabled=Boolean(searchJob);remove.addEventListener('click',()=>{queue.delete(f);renderQueue();});const small=document.createElement('small');small.textContent=item.status;div.append(strong,query,remove,small);if(searchJob&&item.status==='检索中…'){const cancel=document.createElement('button');cancel.textContent='取消检索';cancel.addEventListener('click',async()=>{try{const cancelId=searchJob;searchCancelRequested=cancelId;await api('/api/cancel/'+cancelId,{});queue.get(f).status='取消请求已提交，等待网络返回';renderQueue();}catch(error){notice(error.message,true);}});div.append(cancel);}$('queue').append(div);}}
async function search(f){if(searchJob)return;let id;queue.get(f).status='检索中…';searchJob='starting';renderQueue();$('searchTitle').textContent=f+' · PubChem';$('searchStatus').textContent='查询公开记录；可能需要等待网络与批次重试';$('searchExport').disabled=true;$('compounds').replaceChildren();$('compoundDetail').textContent='正在检索…';searchData=null;try{const response=await api('/api/search',{formula:f,ion_mode:$('mode').value.endsWith('+')?'positive':'negative'});id=response.id;searchJob=id;searchCancelRequested=null;renderQueue();const state=await poll(id,()=>searchJob===id);if(!state)return;if(state.status==='error'&&searchCancelRequested!==id)throw Error(state.error);if(state.status==='cancelled'||searchCancelRequested===id){queue.get(f).status='已取消';$('searchStatus').textContent='已取消，未回填结果';$('compoundDetail').textContent='可重新查询。';return;}const result=state.result,record=result.success?.[f];if(!record){const d=result.failed_details?.[f];throw Error(d?.category==='no_compounds'?'PubChem 无匹配记录（不等于化合物不存在）':d?.message||'检索失败，可重试');}searchData=record;const partial=Boolean(result.partial?.[f])||record.metadata?.status==='partial';queue.get(f).status=partial?'部分结果 · 可重试补拉':'响应完成';$('searchStatus').textContent=(partial?'部分结果：批次或同义词存在缺口，排序可能变化':'响应完成：数据库覆盖与结构鉴定仍需复核')+` · ${record.results.length} 条`;$('searchExport').disabled=false;renderCompounds(record);}catch(error){queue.get(f).status='失败 · 保留待重试';$('searchStatus').textContent=error.message;$('compoundDetail').textContent='失败信息已保留，可重试。';notice(error.message,true);}finally{searchJob=null;renderQueue();}}
function renderCompounds(data){$('compounds').replaceChildren();for(const row of data.results){const button=document.createElement('button');button.textContent=row.title||row.iupac_name||'名称缺失';const small=document.createElement('small');small.textContent=`CID ${row.cid??'缺失'} · 启发分 ${row.final_score??'缺失'}`;button.append(small);button.addEventListener('click',()=>compound(row));$('compounds').append(button);}if(data.results.length)compound(data.results[0]);else $('compoundDetail').textContent='检索响应无通过当前筛选的记录。原始数据保留在缓存。';}
function compound(row){const container=$('compoundDetail');container.replaceChildren();const title=document.createElement('h3');title.textContent=row.title||row.iupac_name||'名称缺失';const hint=document.createElement('p');hint.textContent='启发排序分 ≠ 鉴定概率。同义词缺口可能影响排序。';const dl=document.createElement('dl');for(const [label,value]of [['CID',row.cid],['IUPAC 名称',row.iupac_name],['分子量 / 平均 Da',row.molecular_weight],['单同位素质量 Da',row.monoisotopic_mass],['启发排序分',row.final_score],['同义词状态',row.synonyms_complete===true?'完整响应':row.synonyms_complete===false?'缺失 / 部分':'未记录'],['SMILES',row.canonical_smiles||row.isomeric_smiles],['InChI',row.inchi],['同义词',(row.synonyms||[]).slice(0,25).join(' / ')||null]]){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value??'缺失';dl.append(dt,dd);}container.append(title,hint,dl);if(Number.isInteger(row.cid)&&row.cid>0){const a=document.createElement('a');a.textContent='在 PubChem 核对记录 ↗';a.href='https://pubchem.ncbi.nlm.nih.gov/compound/'+row.cid;a.target='_blank';a.rel='noopener noreferrer';container.append(a);}}
async function boot(){try{config=await api('/api/config');elementInputs();adductInputs();try{const draft=JSON.parse(localStorage.getItem('mass-finding-draft-v2')||'null');if(draft){validParams(draft);applyParams(draft);$('draftState').textContent='已恢复本机参数草稿 · 尚无结果';}}catch(_error){notice('旧参数草稿无效，已使用默认示例参数。');}updateHints();$('analysisForm').addEventListener('submit',analyze);$('analysisForm').addEventListener('input',changed);$('mode').addEventListener('change',()=>{adductInputs();changed();});$('cancel').addEventListener('click',async()=>{if(job)try{const cancelId=job;cancelRequested=cancelId;await api('/api/cancel/'+cancelId,{});notice('取消请求已提交，正在停止枚举。');}catch(error){notice(error.message,true);}});$('example').addEventListener('click',loadExample);$('emptyExample').addEventListener('click',loadExample);$('importButton').addEventListener('click',()=>$('importFile').click());$('importFile').addEventListener('change',importFile);$('formulaFilter').addEventListener('input',()=>{page=1;render();});$('prev').addEventListener('click',()=>{page--;render();});$('next').addEventListener('click',()=>{page++;render();});$('jsonExport').addEventListener('click',()=>download(JSON.stringify(current,null,2),'mass-finding-results.json','application/json'));$('csvExport').addEventListener('click',()=>download(csv(current),'mass-finding-results.csv','text/csv;charset=utf-8'));$('addSearch').addEventListener('click',()=>{if(selected){addQueue(formula(selected));view('search');}});$('addManual').addEventListener('click',()=>addQueue($('manualFormula').value.trim()));for(const nav of document.querySelectorAll('.nav'))nav.addEventListener('click',()=>view(nav.dataset.view));$('searchExport').addEventListener('click',()=>download(JSON.stringify(searchData,null,2),'pubchem-results.json','application/json'));$('settingsOpen').addEventListener('click',()=>$('settings').showModal());$('settingsClose').addEventListener('click',()=>$('settings').close());$('precision').addEventListener('change',render);$('pageSize').addEventListener('change',()=>{page=1;render();});$('clearDraft').addEventListener('click',()=>{try{localStorage.removeItem('mass-finding-draft-v2');$('draftState').textContent='参数草稿已清除';}catch(error){notice(error.message,true);}});}catch(error){notice('工作台初始化失败：'+error.message+'。请确认本机服务仍在运行并刷新。',true);$('analyze').disabled=true;}}
boot();
